# SPDX-License-Identifier: AGPL-3.0-or-later
# erida edit - пул голосования: Основные карты (Backmen + Erida)

- type: gameMapPool
  id: DefaultMapPool
  maps:
  - BackmenAspid
  - BackmenBox
  - BackmenDelta
  - BackmenHive
  - BackmenKettle
  - BackmenRook
  - BackmenShoukou
  - BackmenTortuga
  - EridaAmber
  - EridaAspid
  - EridaBagel
  - EridaBox
  - EridaConvex
  - EridaElkridge
  - EridaFland
  - EridaHive
  - EridaKettle
  - EridaLoop
  - EridaMarathon
  - EridaMeta
  - EridaOasis
  - EridaOmega
  - EridaPacked
  - EridaPlasma
  - EridaRook
  - EridaShoukou
  - EridaTortuga
  - EridaTrain
  - EridaDelta
  - CentComm